const DEFAULT_SETTINGS = [
  ['app_title', 'Catering CRM', 'Titulek aplikace v prohlížeči'],
  ['app_logo_data_url', '', 'Logo aplikace jako data URL'],
  ['app_color_theme', 'ocean', 'Barevná šablona aplikace'],
  ['app_document_font_family', 'syne', 'Písmo pro tiskové výstupy a PDF materiály'],
  ['public_ga4_measurement_id', '', 'GA4 Measurement ID pro veřejné části aplikace'],
  ['voucher_design_style', 'classic', 'Vzhled tiskového poukazu'],
  ['voucher_shop_enabled', 'false', 'Veřejný prodej poukazů zapnutý'],
  ['voucher_shop_values', '1000,2000,3000,5000,10000', 'Povolené hodnoty poukazů ve veřejném shopu'],
  ['voucher_shop_min_amount', '500', 'Minimální hodnota poukazu ve veřejném shopu'],
  ['voucher_shop_offers', '', 'Nabízené typy poukazů ve veřejném shopu'],
  ['voucher_shop_validity_months', '12', 'Výchozí platnost koupených poukazů v měsících'],
  ['voucher_shop_terms_text', '', 'Podmínky veřejného prodeje poukazů'],
  ['voucher_shop_logo_data_url', '', 'Logo veřejné stránky pro prodej poukazů'],
  ['voucher_shop_brand_title', '', 'Název veřejné stránky pro prodej poukazů'],
  ['voucher_shop_header_subtitle', 'Poukazy · Praha', 'Podtitulek v hlavičce veřejného voucher shopu'],
  ['voucher_shop_hero_eyebrow', '[01] - Dárkové poukazy', 'Malý text nad hero nadpisem voucher shopu'],
  ['voucher_shop_hero_title', 'Darujte chuť, ne věci.', 'Hero nadpis voucher shopu'],
  ['voucher_shop_hero_highlight', 'chuť', 'Zvýrazněná část hero nadpisu voucher shopu'],
  ['voucher_shop_hero_text', 'Hodnotové i zážitkové poukazy. Vyberte částku, doplňte jméno a vzkaz, náhled poukazu uvidíte ještě před objednáním.', 'Hero popis voucher shopu'],
  ['voucher_shop_how_title_1', 'Vyberte poukaz', 'Krok 1 ve voucher shopu'],
  ['voucher_shop_how_text_1', 'Hodnotový nebo zážitkový poukaz z aktuální nabídky.', 'Popis kroku 1 ve voucher shopu'],
  ['voucher_shop_how_title_2', 'Personalizujte', 'Krok 2 ve voucher shopu'],
  ['voucher_shop_how_text_2', 'Doplňte jméno, e-mail, vzkaz a fakturační údaje.', 'Popis kroku 2 ve voucher shopu'],
  ['voucher_shop_how_title_3', 'Dokončete objednávku', 'Krok 3 ve voucher shopu'],
  ['voucher_shop_how_text_3', 'Po odeslání vám přijde potvrzení objednávky.', 'Popis kroku 3 ve voucher shopu'],
  ['voucher_shop_footer_title', 'Pojďme spolu obdarovat.', 'Nadpis patičky voucher shopu'],
  ['voucher_shop_terms_title', 'Obchodní podmínky', 'Nadpis stránky obchodních podmínek voucher shopu'],
  ['app_setup_completed_at', '', 'Čas dokončení úvodního setup wizardu'],
  ['app_setup_completed_by', '', 'ID uživatele, který dokončil úvodní setup wizard'],
  ['backup_auto_enabled', 'true', 'Automatické denní zálohy zapnuté'],
  ['backup_auto_time', '02:30', 'Čas automatické zálohy (HH:MM)'],
  ['backup_retention_count', '14', 'Počet uchovávaných JSON záloh'],
  ['backup_last_run_at', '', 'Čas posledního běhu zálohy'],
  ['backup_last_status', '', 'Stav posledního běhu zálohy'],
  ['backup_last_error', '', 'Chyba posledního běhu zálohy'],
  ['modul_kalendar', 'true', 'Kalendář akcí a kapacity'],
  ['modul_reporty', 'true', 'Reporty a statistiky'],
  ['modul_faktury', 'true', 'Fakturace'],
  ['modul_archiv', 'true', 'Archiv'],
  ['modul_error_log', 'true', 'Error log'],
  ['modul_email', 'true', 'E-mailovy modul'],
  ['modul_sablony', 'true', 'Šablony zakázek'],
  ['modul_cenik', 'true', 'Ceník'],
  ['modul_pro', 'true', 'Suroviny a receptury'],
  ['modul_vouchers', 'true', 'Poukazy'],
  ['modul_venues', 'true', 'Prostory'],
  ['modul_personal', 'true', 'Personál'],
  ['modul_dokumenty', 'true', 'Dokumenty'],
];

module.exports = { DEFAULT_SETTINGS };
