const DEFAULT_SETTINGS = [
  ['app_title', 'Catering CRM', 'Titulek aplikace v prohlížeči'],
  ['app_logo_data_url', '', 'Logo aplikace jako data URL'],
  ['app_color_theme', 'ocean', 'Barevná šablona aplikace'],
  ['app_document_font_family', 'syne', 'Písmo pro tiskové výstupy a PDF materiály'],
  ['voucher_design_style', 'classic', 'Vzhled tiskového poukazu'],
  ['voucher_shop_enabled', 'false', 'Veřejný prodej poukazů zapnutý'],
  ['voucher_shop_values', '1000,2000,3000,5000,10000', 'Povolené hodnoty poukazů ve veřejném shopu'],
  ['voucher_shop_validity_months', '12', 'Výchozí platnost koupených poukazů v měsících'],
  ['voucher_shop_terms_text', '', 'Podmínky veřejného prodeje poukazů'],
  ['app_setup_completed_at', '', 'Čas dokončení úvodního setup wizardu'],
  ['app_setup_completed_by', '', 'ID uživatele, který dokončil úvodní setup wizard'],
  ['backup_auto_enabled', 'true', 'Automatické denní zálohy zapnuté'],
  ['backup_auto_time', '02:30', 'Čas automatické zálohy (HH:MM)'],
  ['backup_retention_count', '14', 'Počet uchovávaných JSON záloh'],
  ['backup_last_run_at', '', 'Čas posledního běhu zálohy'],
  ['backup_last_status', '', 'Stav posledního běhu zálohy'],
  ['backup_last_error', '', 'Chyba posledního běhu zálohy'],
  ['modul_kalendar', 'true', 'Kalendář akcí a kapacity'],
  ['modul_reporty', 'true', 'Reporty a statistiky'],
  ['modul_faktury', 'true', 'Fakturace'],
  ['modul_archiv', 'true', 'Archiv'],
  ['modul_error_log', 'true', 'Error log'],
  ['modul_email', 'true', 'E-mailovy modul'],
  ['modul_sablony', 'true', 'Šablony zakázek'],
  ['modul_cenik', 'true', 'Ceník'],
  ['modul_pro', 'true', 'Suroviny a receptury'],
  ['modul_vouchers', 'true', 'Poukazy'],
  ['modul_venues', 'true', 'Prostory'],
  ['modul_personal', 'true', 'Personál'],
  ['modul_dokumenty', 'true', 'Dokumenty'],
];

module.exports = { DEFAULT_SETTINGS };
