ALTER TABLE zakazky
  ADD COLUMN IF NOT EXISTS archivovano BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE klienti
  ADD COLUMN IF NOT EXISTS archivovano BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE personal
  ADD COLUMN IF NOT EXISTS archivovano BOOLEAN NOT NULL DEFAULT false;
